# Generated by Django 4.1.5 on 2023-01-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='name',
            field=models.TextField(default='программист'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='published_at',
            field=models.DateTimeField(default='2003-10-07T00:00:00+0400'),
        ),
    ]
