# Generated by Django 4.1.5 on 2023-01-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_vacancy_name_vacancy_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='published_at',
        ),
    ]
